<div class="page-header clearfix">
    <h2 class="pull-left">Orders</h2>
    <a href="/orders/new" class="btn btn-success pull-right">
        Create Order</a>
</div>

<table class="table table-striped clearfix">
    <thead>
    <tr>
        <th>#</th>
        <th>Order Number</th>
        <th>Customer</th>
        <th>Description</th>
        <th class="text-right">Total</th>
    </tr>
    </thead>
    <?php foreach ($this->orders as $order): ?>
        <tr>
            <td>
                <a href="/orders/view/<?= $this->escapeHtmlAttr($order->getId()) ?>">
                    <?= $this->escapeHtml($order->getId()) ?></a>
            </td>
            <td><?= $this->escapeHtml($order->getOrderNumber()) ?></td>
            <td>
                <a href="/customers/edit/<?= $this->escapeHtmlAttr($order->getCustomer()->getId()) ?>">
                    <?= $this->escapeHtml($order->getCustomer()->getName()) ?></a>
            </td>
            <td><?= $this->escapeHtml($order->getDescription()) ?></td>
            <td class="text-right">
                $ <?= number_format($order->getTotal(), 2) ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
